#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2011 Thomas Schreiber
#
# Contributors:
#    Greg Haynes
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# potluck
# by Thomas Schreiber <ubiquill@gmail.com>
#
# A GUI front-end for Archlinux's Pacman and AUR.

import sys

from PyQt4.QtGui import QApplication

from MainWindow import Main




if __name__ == '__main__':
    app = QApplication(sys.argv)
    mw = Main(app)
    mw.show()
    sys.exit(app.exec_())



# vim: set ts=4 sw=4 noet:
